version: '3.8'

services:
  springbootapp:
    image: openjdk:21
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./target/Project2Boot-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
