version: '3.8'

services:
  springbootapp:
    build: .
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root